export const KEPLER_CONFIG = {
  version: 'v1',
  config: {
    visState: {
      layers: [
        {
          id: 'buildings-3d',
          type: 'geojson',
          config: {
            dataId: 'spb-buildings',
            label: 'Здание СПб',
            color: [227, 6, 17],
            columns: { geojson: '_geojson' },
            isVisible: true,
            visConfig: {
              opacity: 0.9,
              strokeOpacity: 0.4,
              thickness: 0.3,
              strokeColor: [255, 50, 50],
              colorRange: {
                name: 'MTS Height Gradient',
                type: 'sequential',
                category: 'Custom',
                colors: [
                  '#0a0e14', '#1a0a2e', '#2d0a4e',
                  '#8b0000', '#cc0000', '#e30611',
                  '#ff4d00', '#ff8c00', '#ffc200', '#ffe066',
                ],
              },
              radius: 10,
              sizeRange: [0, 10],
              radiusRange: [0, 50],
              heightRange: [0, 120],
              elevationScale: 1,
              stroked: true,
              filled: true,
              enable3d: true,
              wireframe: false,
            },
            colorField: { name: 'final_height_m', type: 'real' },
            colorScale: 'quantize',
            heightField: { name: 'final_height_m', type: 'real' },
            heightScale: 'linear',
          },
          visualChannels: {
            colorField: { name: 'final_height_m', type: 'real' },
            colorScale: 'quantize',
            sizeField: null,
            sizeScale: 'linear',
            strokeColorField: null,
            strokeColorScale: 'quantile',
            heightField: { name: 'final_height_m', type: 'real' },
            heightScale: 'linear',
          },
        },
        {
          id: 'zones-layer',
          type: 'geojson',
          config: {
            dataId: 'mts-zones',
            label: 'Зоны МТС',
            isVisible: false,
            columns: { geojson: '_geojson' },
            color: [57, 255, 20],
            visConfig: {
              opacity: 0.6,
              strokeOpacity: 0.8,
              thickness: 0.5,
              filled: true,
              stroked: false,
              enable3d: false,
              colorRange: {
                name: 'Zones',
                type: 'sequential',
                category: 'Custom',
                colors: ['#39FF14', '#FFD700', '#FF1A2E'],
              },
            },
            colorField: { name: 'zone_id', type: 'integer' },
            colorScale: 'quantize',
          },
          visualChannels: {
            colorField: { name: 'zone_id', type: 'integer' },
            colorScale: 'quantize',
            sizeField: null,
            sizeScale: 'linear',
            strokeColorField: null,
            strokeColorScale: 'quantile',
            heightField: null,
            heightScale: 'linear',
          },
        },
      ],
      interactionConfig: {
        tooltip: {
          fieldsToShow: {
            'spb-buildings': [
              { name: 'gkh_address', format: null },
              { name: 'final_height_m', format: '.1f' },
              { name: 'gkh_floor_count_max', format: null },
              { name: 'area_sq_m', format: '.0f' },
              { name: 'B_purpose_of_building', format: null },
              { name: 'feat_building_type', format: null },
            ],
          },
          compareMode: false,
          compareType: 'absolute',
          enabled: true,
        },
        brush: { size: 0.5, enabled: false },
        geocoder: { enabled: false },
        coordinate: { enabled: false },
      },
      filters: [],
      layerBlending: 'normal',
      splitMaps: [],
    },
    mapState: {
      bearing: -20,
      dragRotate: true,
      latitude: 59.935,
      longitude: 30.32,
      pitch: 55,
      zoom: 14,
      isSplit: false,
    },
    mapStyle: {
      topLayerGroups: {},
      visibleLayerGroups: {
        label: true,
        road: true,
        border: false,
        building: false,
        water: true,
        land: true,
      },
      threeDBuildingColor: [10, 10, 10],
      backgroundColor: [0, 0, 0],
      mapStyles: {
        'maptiler-dark': {
          id: 'maptiler-dark',
          label: 'MapTiler Dark',
          url: `https://api.maptiler.com/maps/dataviz-dark/style.json?key=${import.meta.env?.VITE_MAPTILER_KEY ?? ''}`,
          icon: '',
          layerGroups: [],
        },
      },
      styleType: 'maptiler-dark',
    },
  },
}